welcome:
    pattern: /
    defaults:
        _controller: "FrameworkBundle:Redirect:redirect"
        route: eklerni_cas_login
        permanent: true

eklerni_cas:
    resource: "@EklerniCASBundle/Resources/config/routing.xml"
    prefix:   /cas

eklerni_rest:
    resource: "@EklerniRESTBundle/Resources/config/routing.xml"
    prefix:   /api/

eklerni_front:
    resource: "@EklerniFrontBundle/Resources/config/routing.xml"
    prefix:   /front/

eklerni_back:
    resource: "@EklerniBackBundle/Resources/config/routing.xml"
    prefix:   /back/
