security:
    encoders:
        Eklerni\CASBundle\Entity\Enseignant:
            algorithm:  sha512
        Eklerni\CASBundle\Entity\Eleve:
            algorithm:  sha512

    role_hierarchy:
        ROLE_ELEVE:       ROLE_ELEVE
        ROLE_ENSEIGNANT:  [ROLE_ENSEIGNANT, ROLE_ELEVE]

    providers:
        chain_provider:
            chain:
                providers: [enseignants, eleves]
        enseignants:
            entity: { class: EklerniCASBundle:Enseignant, property: username }
        eleves:
            entity: { class: EklerniCASBundle:Eleve, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        cas:
            pattern:  ^/
            form_login:
                login_path: eklerni_cas_login
                check_path: eklerni_cas_login_check
                csrf_provider: form.csrf_provider
            logout:
                path:   eklerni_cas_logout
                target: eklerni_cas_login
            anonymous:  true

    access_control:
        - { path: ^/cas, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back, roles: IS_AUTHENTICATED_ANONYMOUSLY }
