security:
    encoders:
        Eklerni\CASBundle\Entity\Enseignant:
            algorithm:  sha512
        Eklerni\CASBundle\Entity\Eleve:
            algorithm:  sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ENSEIGNANT
        ROLE_SUPER_ADMIN: [ROLE_ELEVE, ROLE_ENSEIGNANT, ROLE_ALLOWED_TO_SWITCH]

    providers:
        enseignants:
            entity: { class: EklerniCASBundle:Enseignant, property: username }
        eleves:
            entity: { class: EklerniCASBundle:Eleve, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        cas:
            pattern:  ^/admin
            #anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            #form_login:
            #    login_path: login
            #    check_check: login_check
            #    csrf_provider: form.csrf_provider
            #logout:
            #    path:   _demo_logout
            #    target: _demo

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cas, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/front, roles: ROLE_ELEVE }
        - { path: ^/back, roles: ROLE_ENSEIGNANT }
